name: vsce-rc

on:
  push:
    branches:
      - release/*

  workflow_dispatch:

jobs:
  build-vsce-rc:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      channel: rc
      lsp-program-version: latest
      lsp-build-configuration: Release
      preview-flag: false
      pre-release-build: true
