name: vsce-develop

on:
  push:
    branches:
      - develop
      - feature/**
      - fix/**

  workflow_dispatch:

jobs:
  build-vsce-develop:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      channel: develop
      lsp-program-version: latest
      lsp-build-configuration: Debug
      preview-flag: true
      pre-release-build: true
