name: vsce-release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build-vsce-release:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      channel: release
      lsp-program-version: latest
      lsp-build-configuration: Release
      preview-flag: false
      pre-release-build: false
