name: vsce-develop

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  build-vsce-develop:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      lsp-program-version: latest
      lsp-build-configuration: Debug
      preview-build: true
