name: develop

on:
  push:
    branches:
      - v1.0-preview/develop
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      build-configuration: Debug
      preview-build: true

