name: vsce-develop

on:
  push:
    branches:
      - release/v*
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build-vsce-release:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      lsp-program-version: latest
      lsp-build-configuration: Release
      preview-flag: false
      pre-release-build: false
