name: vsce-v1-preview-develop

on:
  push:
    branches:
      - v1.0-preview/develop
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  build-vsce-v1-preview-develop:
    uses: ./.github/workflows/build_vscode_extension.yml
    secrets: inherit
    with:
      lsp-build-configuration: Debug
      preview-build: true

